### ISSUE TITLE
框出的轮廓没有被白色填充

### ISSUE THREAD

**Issue by Levigty** [SamuelYG/trimap_generate#1]
请问利用鼠标框轮廓时有什么要注意的嘛？

**Comment by YangGangSam** [comment]
> 请问利用鼠标框轮廓时有什么要注意的嘛？

鼠标必须框出一个封闭的轮廓。以这里的 test.png 为例，左侧、下方边缘也要用鼠标去画。
根据 circle dilate 里的参数，框轮廓时，鼠标可以稍微在边缘内侧一些。
还有就是，最终生成的 trimap 可能拿到具体工程里效果不一定好，因为有些细节没有考虑到🌚。你可以去搜索一个封装好的 Robust Matting 的程序，手动标记 trimap 效果会好些。

**Comment by Levigty** [comment]
感谢回复，我之前有看代码，画框时是封闭的，但是并没有被填充。是我有漏掉什么步骤吗还是因为鼠标点并不是完全封闭？感谢指引Robust Matting 程序，我回去看一下。

**Comment by YangGangSam** [comment]
因为“线”是靠一个个圆点连起来的，框的时候尽量慢些，或者重复画一下试试
